# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c415588647fb5f4fa935b7da7316a6bdfefa7c5c718e978e9010d3f5afb7f860fc4f71e139d1220a40ec0e00e678a0e9c4049df0149939f472a721ce34273c20

test:
  secret_key_base: 22165717dfc3f35e6bb94bd08922f76701a7d5c30c50efc0ede91c381e0e47673a4cceaf1d356204dd5cf6e733c1acdb12a1601ed3124ac14bebd71724a1c963

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
